### ISSUE TITLE
Speed wise?

### ISSUE THREAD

**Issue by RichThePR1NCE** [Abregud/All-Chains-EthereumX-Sniping-Bot#5]
Hi What's the speed of the bot looking like nowadays? With BananaGun and Unibot, I was wondering if this could sniper block 0.

Thanks

**Comment by Abregud** [comment]
Hey man, the free sniper is about block 2 and 3. The paid one of course is better than even Unibot due to functions that get you out if they gonna rug. But free is free

**Comment by Abregud** [comment]
If you want the real deal here you get it: https://defix.shop/portfolio/crosschain-sniping-bot/

**Comment by AzizLeBG** [comment]
Link doesn't work, I'm trying to buy one with SOL available, Please send me a DM on Telegram @RichThePR1NCE or Discord .azizlebg so we can I buy the full chain program
